name: SSM Parameter Update Workflow

on:
  push:
    branches:
      - main

jobs:
  ssm-parameter-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <AWS_REGION> # Replace with your desired AWS region

      - name: Update SSM Parameter
        run: |
          aws ssm put-parameter \
            --name <PARAMETER_NAME> \
            --value <NEW_PARAMETER_VALUE> \
            --type <PARAMETER_TYPE> \
            --overwrite

